{
  description = "Project environment generated by Plainix";

  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
  inputs.plainix = {
    url = "github:yawarakatai/plainix";
    inputs.nixpkgs.follows = "nixpkgs";
  };

  outputs = inputs:
    let
      plainixOutputs = inputs.plainix.lib.project inputs ./plainix.nix;
      systems = [ "x86_64-linux" ];
      forAllSystems = inputs.nixpkgs.lib.genAttrs systems;
      projectPackages = forAllSystems (system:
        let
          pkgs = inputs.nixpkgs.legacyPackages.${system};
        in
        rec {
          hanas = pkgs.callPackage ./nix/hanas.nix { };
          aivisspeech-engine = pkgs.callPackage ./nix/aivisspeech-engine.nix { };
          default = hanas;
        });
    in
    plainixOutputs
    // {
      packages = projectPackages;
      apps = forAllSystems (system: {
        hanas = {
          type = "app";
          program = "${projectPackages.${system}.hanas}/bin/hanas";
          meta.description = "Run hanas";
        };
        aivisspeech-engine = {
          type = "app";
          program = "${projectPackages.${system}.aivisspeech-engine}/bin/aivisspeech-engine";
          meta.description = "Run AivisSpeech Engine 1.2.0";
        };
        default = {
          type = "app";
          program = "${projectPackages.${system}.hanas}/bin/hanas";
          meta.description = "Run hanas";
        };
      });
    };
}
